#!/usr/bin/env bash
# Regression coverage for issue #1: 90-remove-ollama.sh must fail CLOSED.
#
# The property under test is not "the preflight returns the right boolean" but
# "nothing destructive runs unless the replacement stack genuinely works". Every
# negative case therefore asserts on the *call log*, not just the exit status.
set -uo pipefail

TEST_ROOT="${TEST_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
REPO_ROOT="${REPO_ROOT:-$(cd "$TEST_ROOT/.." && pwd)}"
source "$TEST_ROOT/lib/harness.sh"
source "$TEST_ROOT/lib/mockenv.sh"

# Read by run_suite in the sourced harness.
# shellcheck disable=SC2034
SUITE_NAME="90-remove-ollama.sh preflight (#1)"

API="$TEST_ROOT/fixtures/api"

setup_test() {
  mock_init
  use_gpu dual_a4000
  services_active "llama-swap"
  export PREFLIGHT_TIMEOUT=5
}

# Write a claude-code-local.env pointing at a given base URL.
write_env() {
  local url="$1" model="${2:-qwen3-coder-30b-a3b-instruct}"
  cat >"$RIG_DIR/claude-code-local.env" <<EOF
# Generated by llm-rig.
export ANTHROPIC_BASE_URL="$url"
export ANTHROPIC_AUTH_TOKEN="local"
export ANTHROPIC_DEFAULT_SONNET_MODEL="$model"
EOF
}

load_preflight() {
  # shellcheck source=/dev/null
  source "$REPO_ROOT/lib/detect.sh"
  # shellcheck source=/dev/null
  source "$REPO_ROOT/lib/preflight.sh"
}

# Route a fully working stack at the given base URL.
route_healthy_stack() {
  local base="$1"
  mock_route_file GET  "$base/v1/models"   200 "$API/models_ok.json"
  mock_route_file POST "$base/v1/messages" 200 "$API/messages_tool_use.json"
}

run_removal() { run bash -c "printf 'y\n' | bash '$REPO_ROOT/90-remove-ollama.sh'"; }

# --- endpoint resolution ----------------------------------------------------

test_resolves_native_endpoint_from_env_file() {
  load_preflight
  write_env "http://127.0.0.1:8081"
  assert_eq "$(preflight_endpoint "$RIG_DIR/claude-code-local.env")" \
            "http://127.0.0.1:8081" "native endpoint"
}

test_resolves_litellm_endpoint_from_env_file() {
  # The original bug: the script always printed PROXY_PORT (4000) regardless of
  # which mode was configured. Both modes must resolve to their own port.
  load_preflight
  write_env "http://127.0.0.1:4000"
  assert_eq "$(preflight_endpoint "$RIG_DIR/claude-code-local.env")" \
            "http://127.0.0.1:4000" "LiteLLM endpoint"
}

test_falls_back_to_native_when_env_file_missing() {
  load_preflight
  assert_eq "$(preflight_endpoint "$RIG_DIR/nonexistent.env")" \
            "http://127.0.0.1:8081" "native fallback"
}

test_strips_trailing_slash_from_base_url() {
  load_preflight
  write_env "http://127.0.0.1:8081/"
  assert_eq "$(preflight_endpoint "$RIG_DIR/claude-code-local.env")" \
            "http://127.0.0.1:8081" "normalised base URL"
}

test_env_file_is_parsed_not_executed() {
  # This runs immediately before destructive work, so sourcing whatever is in
  # the file would be a needless foot-gun.
  load_preflight
  cat >"$RIG_DIR/claude-code-local.env" <<'EOF'
export ANTHROPIC_BASE_URL="http://127.0.0.1:4000"
touch "$SANDBOX/env-file-was-executed"
EOF
  preflight_endpoint "$RIG_DIR/claude-code-local.env" >/dev/null
  [[ -e "$SANDBOX/env-file-was-executed" ]] && {
    _fail "env file was executed rather than parsed"; return 1; }
  return 0
}

test_prefers_configured_model_when_server_serves_it() {
  load_preflight
  write_env "http://127.0.0.1:8081" "devstral-small-2-24b-instruct-2512"
  local avail; avail=$'qwen3-coder-30b-a3b-instruct\ndevstral-small-2-24b-instruct-2512'
  assert_eq "$(preflight_model "$RIG_DIR/claude-code-local.env" "$avail")" \
            "devstral-small-2-24b-instruct-2512" "configured model"
}

test_ignores_configured_model_the_server_does_not_serve() {
  # Verifying a model that isn't loaded would prove nothing about the stack.
  load_preflight
  write_env "http://127.0.0.1:8081" "a-model-that-was-never-downloaded"
  local avail; avail=$'qwen3-coder-30b-a3b-instruct'
  assert_eq "$(preflight_model "$RIG_DIR/claude-code-local.env" "$avail")" \
            "qwen3-coder-30b-a3b-instruct" "fallback to a served model"
}

# --- individual checks ------------------------------------------------------

test_models_check_rejects_empty_model_list() {
  load_preflight
  mock_route_file GET "/v1/models" 200 "$API/models_empty.json"
  run preflight_check_models "http://127.0.0.1:8081"
  assert_fails "zero models must not pass"
}

test_models_check_rejects_unreachable_router() {
  load_preflight
  run preflight_check_models "http://127.0.0.1:8081"
  assert_fails "unreachable router must not pass"
}

test_messages_check_rejects_load_failure() {
  load_preflight
  mock_route_file POST "/v1/messages" 500 "$API/error_500.json"
  run preflight_check_messages "http://127.0.0.1:8081" "some-model"
  assert_fails "HTTP 500 must not pass"
}

test_tool_call_check_rejects_text_only_response() {
  # The heart of issue #1: a valid, healthy-looking answer with no tool_use.
  load_preflight
  mock_route_file POST "/v1/messages" 200 "$API/messages_text_only.json"
  run preflight_check_tool_call "http://127.0.0.1:8081" "some-model"
  assert_fails "text-only response must not pass"
}

test_tool_call_check_accepts_tool_use_response() {
  load_preflight
  mock_route_file POST "/v1/messages" 200 "$API/messages_tool_use.json"
  run preflight_check_tool_call "http://127.0.0.1:8081" "some-model"
  assert_ok "tool_use response must pass"
}

# --- full script: fail-closed guarantees ------------------------------------

test_active_service_with_zero_models_does_not_remove_ollama() {
  # llama-swap is active, which is all the OLD guard checked.
  write_env "http://127.0.0.1:8081"
  mock_route_file GET "/v1/models" 200 "$API/models_empty.json"
  run_removal
  assert_fails "removal must abort" || return 1
  assert_contains "$RUN_OUTPUT" "Preflight FAILED" "diagnostic" || return 1
  assert_no_destructive_calls
}

test_text_only_model_does_not_remove_ollama() {
  write_env "http://127.0.0.1:8081"
  mock_route_file GET  "/v1/models"   200 "$API/models_ok.json"
  mock_route_file POST "/v1/messages" 200 "$API/messages_text_only.json"
  run_removal
  assert_fails "removal must abort" || return 1
  assert_contains "$RUN_OUTPUT" "tool_use" "diagnostic names the failure" || return 1
  assert_no_destructive_calls
}

test_unreachable_endpoint_does_not_remove_ollama() {
  write_env "http://127.0.0.1:8081"
  run_removal
  assert_fails "removal must abort" || return 1
  assert_no_destructive_calls
}

test_model_that_fails_to_load_does_not_remove_ollama() {
  write_env "http://127.0.0.1:8081"
  mock_route_file GET  "/v1/models"   200 "$API/models_ok.json"
  mock_route_file POST "/v1/messages" 500 "$API/error_500.json"
  run_removal
  assert_fails "removal must abort" || return 1
  assert_no_destructive_calls
}

test_litellm_configuration_is_probed_on_its_own_port() {
  # A healthy stack on :4000 must be found there. If the script still probed
  # PROXY_PORT unconditionally -- or LLAMA_PORT unconditionally -- one of these
  # two tests fails.
  write_env "http://127.0.0.1:4000"
  route_healthy_stack "http://127.0.0.1:4000"
  run bash -c "printf 'n\n' | bash '$REPO_ROOT/90-remove-ollama.sh'"
  assert_contains "$RUN_OUTPUT" "127.0.0.1:4000" "probed endpoint" || return 1
  assert_not_contains "$RUN_OUTPUT" "Preflight FAILED" "preflight should pass"
}

test_native_configuration_is_probed_on_its_own_port() {
  write_env "http://127.0.0.1:8081"
  route_healthy_stack "http://127.0.0.1:8081"
  run bash -c "printf 'n\n' | bash '$REPO_ROOT/90-remove-ollama.sh'"
  assert_contains "$RUN_OUTPUT" "127.0.0.1:8081" "probed endpoint" || return 1
  assert_not_contains "$RUN_OUTPUT" "Preflight FAILED" "preflight should pass"
}

test_declining_the_prompt_removes_nothing() {
  write_env "http://127.0.0.1:8081"
  route_healthy_stack "http://127.0.0.1:8081"
  run bash -c "printf 'n\n' | bash '$REPO_ROOT/90-remove-ollama.sh'"
  assert_contains "$RUN_OUTPUT" "aborted" "abort message" || return 1
  assert_no_destructive_calls
}

# --- negative control -------------------------------------------------------

test_healthy_stack_does_proceed_to_removal() {
  # Without this, every "no destructive calls" assertion above could be passing
  # for the wrong reason -- e.g. a typo'd assertion pattern that never matches.
  # This proves the detector fires when removal really happens.
  write_env "http://127.0.0.1:8081"
  route_healthy_stack "http://127.0.0.1:8081"
  export MOCK_DPKG_OLLAMA=1
  run_removal
  assert_ok "healthy stack should allow removal" || return 1
  assert_called 'apt-get remove' "ollama package removal"
}

# --- FORCE escape hatch -----------------------------------------------------

test_force_overrides_a_failed_preflight() {
  write_env "http://127.0.0.1:8081"
  mock_route_file GET "/v1/models" 200 "$API/models_empty.json"
  export FORCE=1 MOCK_DPKG_OLLAMA=1
  run_removal
  assert_ok "FORCE=1 should proceed" || return 1
  assert_called 'apt-get remove' "removal proceeded under FORCE"
}

test_force_warns_prominently_before_proceeding() {
  write_env "http://127.0.0.1:8081"
  mock_route_file GET "/v1/models" 200 "$API/models_empty.json"
  export FORCE=1
  run_removal
  assert_contains "$RUN_OUTPUT" "NO working local model" "FORCE warning"
}

run_suite
suite_exit
