#!/usr/bin/env bash
# Install llama-swap (hot model switching in front of llama-server), generate a
# config tuned for long-context agent workloads, and install it as a service
# listening on the LAN.
set -uo pipefail
source "$(dirname "$0")/lib/detect.sh"

# Re-running this while llama-swap holds a model resident would measure ~3GB free
# and compute a NEGATIVE weight budget, producing a config full of bogus
# --n-cpu-moe values. Free the GPUs before sizing anything.
ensure_gpus_idle
detect_hw

mkdir -p "$RIG_DIR/etc" "$RIG_DIR/logs"

# --- install llama-swap -----------------------------------------------------
install_llama_swap() {
  local api="https://api.github.com/repos/mostlygeek/llama-swap/releases/latest"
  local json; json=$(curl -sfL "$api" 2>/dev/null || true)
  local url=""
  if [[ -n "$json" ]] && echo "$json" | jq -e .tag_name >/dev/null 2>&1; then
    local tag; tag=$(echo "$json" | jq -r .tag_name)
    # Asset naming has changed across releases; match broadly rather than
    # assuming a literal "linux_amd64".
    url=$(echo "$json" | jq -r '.assets[].browser_download_url' \
          | grep -iE 'linux' | grep -iE 'amd64|x86_64' | grep -iE '\.tar\.gz$' | head -1)
    [[ -n "$url" ]] && c_info "llama-swap $tag -> $(basename "$url")"
  fi

  if [[ -n "$url" ]]; then
    local tmp; tmp=$(mktemp -d)
    if curl -sfL "$url" -o "$tmp/ls.tar.gz" && tar -xzf "$tmp/ls.tar.gz" -C "$tmp"; then
      local bin; bin=$(find "$tmp" -name 'llama-swap' -type f | head -1)
      if [[ -n "$bin" ]]; then
        sudo install -m755 "$bin" /usr/local/bin/llama-swap
        rm -rf "$tmp"; return 0
      fi
    fi
    rm -rf "$tmp"
    c_warn "release tarball didn't contain the expected binary"
  fi

  # Fallback: build from source. Requires Go, which is a small apt install.
  c_warn "Falling back to building llama-swap from source"
  need go || sudo apt-get install -y -qq golang-go || return 1
  GOBIN=/tmp/gobin go install github.com/mostlygeek/llama-swap@latest 2>/dev/null \
    && sudo install -m755 /tmp/gobin/llama-swap /usr/local/bin/llama-swap && return 0

  c_err "Could not install llama-swap automatically."
  cat <<'EOF'
     Install it manually, then re-run this script:
       https://github.com/mostlygeek/llama-swap/releases
       tar -xzf llama-swap_*_linux_amd64.tar.gz
       sudo install -m755 llama-swap /usr/local/bin/
EOF
  return 1
}

if ! need llama-swap; then
  c_info "Installing llama-swap"
  install_llama_swap || die "llama-swap required; see instructions above"
  c_ok "llama-swap $(llama-swap --version 2>&1 | head -1)"
else
  c_ok "llama-swap already installed"
fi

# --- sizing decisions -------------------------------------------------------
# Context: 64k is the practical floor for Claude Code. Below ~32k you get silent
# tool-call failures rather than errors, which is the worst possible failure mode.
# Measured on 2x A4000: the 30B-A3B MoE is 17.28 GiB, leaving ~9.8 GB for KV.
# Its KV cost at q8_0 is ~48 KB/token (48 layers, 4 KV heads, d=128), so:
#   64k  -> 3.0 GiB      128k -> 6.0 GiB      256k -> 12.0 GiB (too big)
# 128k fits with margin, and long context is exactly what a coding agent eats.
# CTX and KV_RESERVE_MB are settled by detect_hw, BEFORE the weight budget is
# computed, so the model that was selected is the model this context was sized
# against. This block used to re-derive CTX here and silently overwrite an
# explicit user value.

# Even tensor split across identical cards. If your GPUs differ in size, weight
# this by capacity instead.
TENSOR_SPLIT=""
if (( MULTI_GPU )); then
  # Weight the split by FREE memory. Splitting evenly across cards with unequal
  # headroom OOMs the busier one -- here GPU0 is down ~1.2GB to the desktop.
  TENSOR_SPLIT=$(nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits \
                 | awk '{print $1}' | paste -sd, - )
  c_info "Multi-GPU: $GPU_COUNT cards, tensor-split=$TENSOR_SPLIT, NVLink=$( ((NVLINK)) && echo yes || echo no )"
  ((NVLINK)) || c_warn "No NVLink -- splitting a dense model costs PCIe traffic at every
     layer boundary. Models that fit on ONE card are pinned to one card below."
fi

c_info "ctx=$CTX ($CTX_SOURCE) kv-reserve=${KV_RESERVE_MB}MB ($KV_RESERVE_SOURCE) threads=$THREADS"
c_info "budget=${FIT_TOTAL_MB}MB split / ${FIT_SINGLE_MB}MB single"

# --- generate llama-swap config --------------------------------------------
CFG="$RIG_DIR/etc/llama-swap.yaml"
c_info "Generating $CFG"

{
cat <<EOF
# Generated by llm-rig 40-serve.sh for $GPU_NAME (${VRAM_TOTAL_MB}MB VRAM)
# Regenerate with ./40-serve.sh -- hand edits will be overwritten.

healthCheckTimeout: 900          # big models take a while to load off disk
logLevel: info
startPort: 9100

macros:
  # Shared flags. The comments here are the reasoning -- keep them.
  base: >
    --host 127.0.0.1 --port \${PORT}
    -ngl 999
    -c $CTX
    --threads $THREADS
    --flash-attn on
    --cache-type-k q8_0
    --cache-type-v q8_0
    --cache-reuse 256
    --no-context-shift
    --jinja
    --metrics
    --no-warmup

models:
EOF

# One entry per model found on disk.
found=0
while IFS= read -r gguf; do
  # Skip non-first shards of split models.
  base=$(basename "$gguf")
  [[ "$base" =~ -0000[2-9]-of- ]] && continue
  [[ "$base" =~ -000[1-9][0-9]-of- ]] && continue

  name=$(basename "$(dirname "$gguf")" | sed 's/-GGUF$//i' | tr '[:upper:]' '[:lower:]')
  # Total size of all shards, not just the first one.
  stem="${gguf%%-0000*}"
  if [[ "$stem" != "$gguf" ]]; then
    size_mb=$(du -cm "$stem"-*.gguf 2>/dev/null | tail -1 | cut -f1)
  else
    size_mb=$(du -m "$gguf" | cut -f1)
  fi

  extra=""; envpfx=""; note=""
  is_moe=0
  [[ "$base" =~ [Aa][0-9]+[Bb]|[Mm]o[Ee] ]] && is_moe=1

  if (( MULTI_GPU )); then
    if (( size_mb <= FIT_SINGLE_MB )); then
      # Fits on one card: pin it there. Splitting a model that doesn't need to be
      # split adds PCIe sync at every layer boundary for zero benefit -- and it
      # leaves the second GPU free to serve a different model concurrently.
      envpfx="CUDA_VISIBLE_DEVICES=$BEST_GPU "
      note="pinned to GPU$BEST_GPU (fits in ${FIT_SINGLE_MB}MB, no split overhead)"
    else
      extra="--tensor-split $TENSOR_SPLIT"
      note="split across $GPU_COUNT GPUs"
      # split-mode row can beat layer on 2 cards, but needs working P2P. Layer
      # is the safe default; 60-bench.sh measures whether row is worth it here.
      ((NVLINK)) && extra="$extra --split-mode row"
    fi
  fi

  # MoE: offload EXPERT tensors to CPU rather than dropping whole layers.
  # A 30B-A3B activates ~3B params/token, so CPU-resident experts cost far less
  # than they would in a dense model of the same size. This is what lets a big
  # MoE run on modest VRAM.
  if (( is_moe && size_mb > FIT_TOTAL_MB )); then
    overflow=$(( size_mb - FIT_TOTAL_MB ))
    ncpumoe=$(( overflow / 900 + 1 ))
    extra="$extra --n-cpu-moe $ncpumoe"
    note="$note; ${overflow}MB over budget -> --n-cpu-moe $ncpumoe (experts on CPU)"
  elif (( ! is_moe && size_mb > FIT_TOTAL_MB )); then
    note="$note; WARNING dense model ${size_mb}MB exceeds ${FIT_TOTAL_MB}MB budget"
  fi

  cat <<EOF
  "$name":
    # $(basename "$gguf")  (~${size_mb} MB) -- ${note:-fits in VRAM}
    cmd: |
      ${envpfx}llama-server \${base}
      -m $gguf
      $extra
    ttl: 900
    aliases: ["$name-local"]

EOF
  found=$((found+1))
done < <(find "$MODELS_DIR" -name '*.gguf' -size +100M 2>/dev/null | sort)

if (( found == 0 )); then
  c_warn "No models found in $MODELS_DIR -- run ./30-models.sh first."
fi
} > "$CFG"

c_ok "$found model(s) configured"
grep -E '^  "' "$CFG" | sed 's/:$//' | sed 's/^/    /'

# --- systemd service --------------------------------------------------------
# llama-swap binds LAN-wide; llama-server instances stay on localhost behind it.
c_info "Installing llama-swap.service (LAN on port $LLAMA_PORT)"
sudo tee /etc/systemd/system/llama-swap.service >/dev/null <<EOF
[Unit]
Description=llama-swap (llama.cpp model router)
After=network-online.target llm-gpu-tune.service
Wants=network-online.target

[Service]
Type=simple
User=$USER
Environment=PATH=/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin
Environment=LLAMA_CACHE=$MODELS_DIR/.cache
ExecStart=/usr/local/bin/llama-swap --config $CFG --listen 0.0.0.0:$LLAMA_PORT
Restart=on-failure
RestartSec=5
# Required for --mlock and for large mmap'd models
LimitMEMLOCK=infinity
LimitNOFILE=65535
# Don't let the OOM killer pick the inference server first
OOMScoreAdjust=-500

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable llama-swap.service >/dev/null 2>&1
sudo systemctl restart llama-swap.service
sleep 3

if systemctl is-active --quiet llama-swap; then
  c_ok "llama-swap running on http://0.0.0.0:$LLAMA_PORT"
  echo
  curl -sf "http://127.0.0.1:$LLAMA_PORT/v1/models" | jq -r '.data[].id' 2>/dev/null \
    | sed 's/^/    /' || true
else
  c_err "service failed to start:"
  sudo journalctl -u llama-swap -n 30 --no-pager
fi

# --- firewall ---------------------------------------------------------------
if need ufw && sudo ufw status | grep -q "Status: active"; then
  SUBNET=$(ip -o -f inet addr show | awk '/scope global/ {print $4}' | head -1 \
           | sed 's|\(.*\)\..*/|\1.0/|')
  c_info "Opening $LLAMA_PORT and $PROXY_PORT to $SUBNET only"
  sudo ufw allow from "$SUBNET" to any port "$LLAMA_PORT" proto tcp >/dev/null
  sudo ufw allow from "$SUBNET" to any port "$PROXY_PORT" proto tcp >/dev/null
  c_ok "ufw rules added (LAN only, not the open internet)"
fi

echo
c_info "Endpoint: http://$(hostname -I | awk '{print $1}'):$LLAMA_PORT/v1"
